// The entry point, app.js is like the motherboard of my backend api.
// It connects all the pieces and the ordering of these different parts is important.

// 1. Library dependencies and internal module imports.
const express = require("express");

const mongoose = require("mongoose");

const helmet = require("helmet");
const cors = require("cors");

// joi/celebrate
// If the request doesn’t pass the described validation, celebrate will pass it
// on to the error handler but not to the controller. celebrate has a special
// errors() middleware for sending errors to the client.
const { errors } = require("celebrate");

const { requestLogger, errorLogger } = require("./middlewares/logger");

const centralErrorHandler = require("./middlewares/error-handler");

const indexRouter = require("./routes/index");

// 2. app creation and DB connection.

const app = express();

mongoose
  .connect("mongodb://127.0.0.1:27017/news-explorer_db")
  .then(() => {
    console.log("Connected to MongoDB");
  })
  .catch((err) => {
    console.error(err);
  });

// 3. Preroute middlewares.

// Set security headers for responses.
app.use(helmet());

app.use(cors());
// Parses JSON requests.
app.use(express.json());

app.use(requestLogger);

// 4. Routes to request controllers.

app.use("/", indexRouter);

// 5. Error handling middlewares for things that go wrong in the processing/controllers.

// Winston error logs
// The error logger needs to be enabled after the route handlers and before the error handlers.
app.use(errorLogger);

// The errors() middleware will only handle errors generated by celebrate.
// It will pass all other errors further, where the centralized error handler will catch them.
app.use(errors());

app.use(centralErrorHandler);

// 6. Starting the server and begin accepting requests.

const { PORT = 3002 } = process.env;

app.listen(PORT, () => {
  console.log(`Listening on port: ${PORT}`);
});
